run:
    timeout: 5m
    tests: true

linters:
    enable:
        - errcheck
        - gosimple
        - govet
        - ineffassign
        - staticcheck
        - unused
        - gofmt
        - goimports
        - misspell
        - unconvert
        - bodyclose
        - noctx
        - prealloc

linters-settings:
    gofmt:
        simplify: true
    goimports:
        local-prefixes: github.com/pgEdge/pgedge-rag-server
    misspell:
        locale: US

issues:
    exclude-use-default: false
    max-issues-per-linter: 0
    max-same-issues: 0
