# pgEdge RAG Server Configuration Example for Docker Deployment
# This is a sample configuration file for use with Docker Compose

server:
    listen_address: "0.0.0.0"
    port: 8080
    # TLS configuration (optional)
    # tls:
    #   cert_file: "/etc/pgedge/server.crt"
    #   key_file: "/etc/pgedge/server.key"

# Define one or more RAG pipelines
pipelines:
    - name: "example-docs"
      description: "Example documentation pipeline"
      database:
          host: "postgres"
          port: 5432
          database: "ragdb"
          username: "postgres"
          password: "postgres"
          # For production, use environment variables or secrets:
          # password: "${POSTGRES_PASSWORD}"
      tables:
          - table: "documents"
            text_column: "content"
            vector_column: "embedding"
            # Optional: specify ID column for views or explicit document IDs
            # id_column: "id"

      # Embedding configuration
      embedding_llm:
          provider: "openai"
          model: "text-embedding-3-small"

      # RAG LLM configuration
      rag_llm:
          provider: "anthropic"
          model: "claude-sonnet-4-20250514"

      # Token budget for context documents
      token_budget: 4000

      # Number of results to retrieve
      top_n: 10

      # Search configuration (optional)
      search:
          # Enable hybrid search combining vector + BM25 (default: true)
          hybrid_enabled: true
          # Weight for vector search vs BM25 (0.0 to 1.0, default: 0.5)
          # Set to 1.0 for vector-only search
          vector_weight: 0.7
